from .train_utils_dynamics import single_epoch_rfa_dynamics, single_epoch_attn_dynamics
from .train_utils_dynamics import hook_fn
from .train_utils_lm import single_epoch_rfa_lm, single_epoch_standard_lm